# Generated by Django 6.0.3 on 2026-03-29 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='property_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='property_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
