# Generated by Django 6.0.3 on 2026-04-09 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_app', '0002_website_property_id_website_property_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEORecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('title', '📝 Optimisation des titres'), ('meta', '📄 Meta descriptions'), ('structure', '🏗️ Structure HTML'), ('content', '📖 Contenu'), ('technical', '⚙️ Technique'), ('traffic', '📊 Trafic'), ('engagement', '💬 Engagement'), ('seo', '🔍 SEO'), ('opportunity', '💡 Opportunité')], max_length=50)),
                ('priority', models.CharField(choices=[('high', '⚠️ Haute priorité'), ('medium', '📌 Priorité moyenne'), ('low', '✅ Priorité basse')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_applied', models.BooleanField(default=False)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo_recommendations', to='analytics_app.website')),
            ],
            options={
                'verbose_name': 'Recommandation SEO',
                'verbose_name_plural': 'Recommandations SEO',
                'ordering': ['-created_at'],
            },
        ),
    ]
