# Generated by Django 6.0.3 on 2026-04-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_app', '0003_seorecommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='date_analyse',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
