# Generated by Django 6.0.4 on 2026-04-21 20:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_app', '0004_analysis_date_analyse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysis',
            options={'ordering': ['-date_analyse'], 'verbose_name': 'Analyse', 'verbose_name_plural': 'Analyses'},
        ),
        migrations.AddField(
            model_name='analysis',
            name='resume',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='analysis',
            name='score_contenu',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='analysis',
            name='score_global',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='analysis',
            name='score_technique',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='analysis',
            name='score_trafic',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='analysis',
            name='score_visibilite',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='analysis',
            name='top_keyword',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='total_keywords',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysis',
            name='total_pages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seorecommendation',
            name='analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seo_recommendations', to='analytics_app.analysis'),
        ),
        migrations.AddField(
            model_name='seorecommendation',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Facile'), ('medium', 'Moyenne'), ('hard', 'Difficile')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='seorecommendation',
            name='impact',
            field=models.CharField(choices=[('high', 'Impact élevé'), ('medium', 'Impact moyen'), ('low', 'Impact faible')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='seorecommendation',
            name='status',
            field=models.CharField(choices=[('new', 'Nouvelle'), ('in_progress', 'En cours'), ('done', 'Terminée'), ('ignored', 'Ignorée')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='seorecommendation',
            name='suggested_fix',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='seorecommendation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='website',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='analytics_app.website'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_recommendations', to='analytics_app.analysis'),
        ),
        migrations.AlterField(
            model_name='seorecommendation',
            name='category',
            field=models.CharField(choices=[('title', 'Optimisation des titres'), ('meta', 'Meta descriptions'), ('structure', 'Structure HTML'), ('content', 'Contenu'), ('technical', 'Technique'), ('traffic', 'Trafic'), ('engagement', 'Engagement'), ('seo', 'SEO'), ('opportunity', 'Opportunité')], max_length=50),
        ),
        migrations.AlterField(
            model_name='seorecommendation',
            name='priority',
            field=models.CharField(choices=[('high', 'Haute priorité'), ('medium', 'Priorité moyenne'), ('low', 'Priorité basse')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='website',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websites', to=settings.AUTH_USER_MODEL),
        ),
    ]
